version: "3.3"

services:
  app:
    container_name: srcbot
    build: .
    command: bash bash.sh
    environment:
      API_ID: 17071170
      API_HASH: b599a44ab247af88748ee04dc74756bd
      BOT_TOKEN: 6059578267:AAHv5fADZU77RZx9otBtJApi8VA7mRjjIoY
      SESSION: BQADrPe2owmFJkl4sKXfgA8BmVquhRy4aphDi4cZ8rweiNDRsGeTkbaIU_50Si4t-ZYhsTEgF43pZLWNWo10Jv8_PQgTXeHnWQc897_51gtFrwsrVrzO0pQW_En2YysoQGf-ayTfW1c2gN0VH44xGyuXBgdFDuW4A369uGYp_gPq1R9UW5k1v6mZWAtxeYx0IFo05b0hItuVc_OOXzbouhstgnsaaGhFyLc8_AS_FT-IiYOJAzCbPHtph4KnI4fb6697Ef48HYApHhgdIu0fAeI57_1XcCkBEK1HihRsEa4cVferMAL3yRspmgYiL4Ezo4ei_bstbblYocPss3nb_mf3VgmZiwA
      AUTH: Iamshahrukh5
      FORCESUB: freecourse786
